### ISSUE TITLE
Not building with the latest flutter SDK

### ISSUE THREAD

**Issue by JoeMathew** [matthewtory/trinity-orientation-2018#4]
Had been trying to build it on Mac(Xcode 10.2 installed) but it gives build errors

**Comment by azri92** [comment]
These errors?
```
Compiler message:
lib/photos.dart:916:10: Error: Type 'UploadTaskSnapshot' not found.
  Future<UploadTaskSnapshot> _uploadPicture(BuildContext context, String path) async {
         ^^^^^^^^^^^^^^^^^^
lib/photos.dart:908:39: Error: A value of type 'Future<Image>' can't be assigned to a variable of type 'Image'.
 - 'Future' is from 'dart:async'.
 - 'Image' is from 'dart:ui'.
Try changing the type of the left hand side, or casting the right hand side to 'Image'.
    ui.Image pictureToImage = picture.toImage(image.width, image.height);
                                      ^
lib/photos.dart:927:112: Error: The getter 'future' isn't defined for the class 'StorageUploadTask'.
 - 'StorageUploadTask' is from 'package:firebase_storage/firebase_storage.dart'
 ('file:///.../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_storage-1.1.0+1/lib/firebase_storage.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'future'.
    return ref.putFile(file, StorageMetadata(contentType: 'image/jpeg', customMetadata: {'event': eventData})).future;
                                                                                                               ^^^^^^
Compiler failed on .../trinity-orientation-2018/lib/main.dart
```

**Comment by Xeoos** [comment]
Hello, I have these errors when I try to build. What can I do to solve this ? (I am beginner on Flutter)

> These errors?
> 
> ```
> Compiler message:
> lib/photos.dart:916:10: Error: Type 'UploadTaskSnapshot' not found.
>   Future<UploadTaskSnapshot> _uploadPicture(BuildContext context, String path) async {
>          ^^^^^^^^^^^^^^^^^^
> lib/photos.dart:908:39: Error: A value of type 'Future<Image>' can't be assigned to a variable of type 'Image'.
>  - 'Future' is from 'dart:async'.
>  - 'Image' is from 'dart:ui'.
> Try changing the type of the left hand side, or casting the right hand side to 'Image'.
>     ui.Image pictureToImage = picture.toImage(image.width, image.height);
>                                       ^
> lib/photos.dart:927:112: Error: The getter 'future' isn't defined for the class 'StorageUploadTask'.
>  - 'StorageUploadTask' is from 'package:firebase_storage/firebase_storage.dart'
>  ('file:///.../flutter/.pub-cache/hosted/pub.dartlang.org/firebase_storage-1.1.0+1/lib/firebase_storage.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'future'.
>     return ref.putFile(file, StorageMetadata(contentType: 'image/jpeg', customMetadata: {'event': eventData})).future;
>                                                                                                                ^^^^^^
> Compiler failed on .../trinity-orientation-2018/lib/main.dart
> ```

**Comment by matthewtory** [comment]
This has now been fixed (Build on the Flutter master channel: `flutter channel master`).

**Comment by victoire-hergan** [comment]
Thanks Matthew for your awesome work, perfect project to learn flutter
